### ISSUE TITLE
PP04-Importe: Text wird als "⦿" importiert

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/transcribe#28]
Bei Exmaralda-Files, die von PP04 in Transcribe importiert wurden (nutzen das Preset "PP04" im Type-Token-Parser), fehlt immer wieder Text in Events, der stattdessen durch das Zeichen "⦿" ersetzt wird. Das betrifft global die meisten von ihnen importierten Transkripte, hier als Beispiel aus dem Transkript 4003_GRAG_alt_m_CAF.

Original in Exmaralda sieht die Stelle so aus:
![image](https://user-images.githubusercontent.com/60658004/151207952-0073294d-4cee-4f91-9350-7f49f1aa239a.png)
in transcribe kommt das so an:
![image](https://user-images.githubusercontent.com/60658004/151208096-a4cef115-27ac-4c55-ac76-c2839f273a18.png)

ein bisschen kurios ist, dass - wenn man das Transkript löscht und neu importiert - teilweise ganz andere Events betroffen sind, bei denen das passiert. Bis jetzt konnten wir leider auch nicht eingrenzen, was genau das auslöst - also welche Events davon betroffen sind. Es betrifft aber nur den Transkript-Text, die Annotationen sind importiert worden. Nachdem das scheinbar nur bei PP04-Daten passiert, könnte eventuell irgendein Problem mit dem Type-Token_Parser der Grund sein?

**Comment by MarkusPluschkovits** [comment]
Falls es dir hilft - hab das .exm-File, das hier importiert wird, auf der Cloud in einen Ordner gelegt, den ich mit dir geteilt hab, heißt "4HCB"

**Comment by hcb79** [comment]
@MarkusPluschkovits Ist das Problem gelöst?

**Comment by MarkusPluschkovits** [comment]
> @MarkusPluschkovits Ist das Problem gelöst?

yess, laut PP04 - vielen Dank!
