### ISSUE TITLE
PP03-Preset: Änderung bei Anonymisierung ([Beispiel]O)

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/transcribe#35]
Bitte den Type-Token-Parser anpassen, dass wenn Token als "anonymized" gekennzeichnet werden, und der Buchstabe bei der schließenden Eckklammer fehlt, nur das Token zwischen den Eckklammern als Error angezeigt wird - mit momentanen Stand wird ansonsten nämlich jedes Token ab der linken Klammer als "Other" erkannt

![image](https://user-images.githubusercontent.com/60658004/166645888-6dacdb9c-55d7-4fe6-a3b3-2eacac9a8a8a.png)

**Comment by hcb79** [comment]
Bei welchen Transkript passiert das?

**Comment by MarkusPluschkovits** [comment]
> Bei welchen Transkript passiert das?

scheint bei allen Transkripten der Fall zu sein - sobald der Buchstabe hinter der eckigen Klammer gelöscht wird oder fehlt, werden alle Tokens des Sprechers bis zur nächsten schließenden eckigen Klammer mit Buchstaben dahinter als "anonymized" gekennzeichnet, ideal wäre es wohl, wenn es dann nur die Buchstaben zwischen den eckigen Klammern als Error markieren würde.
