### ISSUE TITLE
Auto-Insert Space before delimiters bei PP04-Preset bei "nonverbal" mit <<xxx>yyy ,> nicht funktional

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/transcribe#38]
Anscheinend wird kein Leerzeichen vor den Delimiter hinzugefügt, wenn es sich um "nonverbal" Token mit spitzen Klammern handelt (Betrifft nur das PP04-PreSet). Also aus Tokenfolgen wie zB

`<<kichernd> WIRKlich,>`

sollte

`<<kichernd> WIRKlich ,>`

werden.

**Comment by hcb79** [comment]
Transkript?

**Comment by MarkusPluschkovits** [comment]
> Transkript?

hab's jetzt selbst noch einmal getestet, bei mir funktioniert das problemlos.. vl. haben die lieben Grazer:innen "auto-inster space before delimiter" nicht angestellt..
