### ISSUE TITLE
Änderung der Abspielgeschwindigkeit keine Wellenform mehr sichtbar

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/transcribe#40]
Wenn die Abspielgeschwindigkeit verändert wird, verschwinden leider die Events + das Oszillogram und erscheinen erst nach dem neu laden des Transkripts wieder.
![image](https://user-images.githubusercontent.com/60658004/168553102-29baee8e-bcc4-4f25-b1b6-56c1e30fb840.png)

**Comment by hcb79** [comment]
War etwas kompliziert ... also ausgiebig testen auf https://transcribe-dev.dioe.at/ und dann den Issue schließen. ;-)

**Comment by MarkusPluschkovits** [comment]
> War etwas kompliziert ... also ausgiebig testen auf https://transcribe-dev.dioe.at/ und dann den Issue schließen. ;-)

hab mich durchprobiert, wirkt sehr gut! Bei den PP04-Transkripten (die, die mit 4 beginnen), kriegt man gar keine Waveform - das wird aber wohl daran liegen, dass die Audiofiles nicht im Verzeichnis von der Demo-DB liegen, oder? Ansonsten hab ich zur Sicherheit die Infos wie im Wiki beschrieben rauskopiert (damit ich das auch mal getestet hab ;)), sind anbei - wenn's aber wirklich nur daran liegen, dass die Audiofiles nicht im Verzeichnis sind, passt jetzt alles und kann man closen ;)

`{
  "settings": {
    "backEndUrl": "https://dioedb.demo.dioe.at",
    "activeSidebarItem": "warnings",
    "showSettings": true,
    "darkMode": false,
    "drawerWidth": 350,
    "emulateHorizontalScrolling": true,
    "eventDockingInterval": 0.05,
    "keyboardShortcuts": {
      "appendEvent": {
        "group": "Editing",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "alt"
        ],
        "key": "+",
        "description": "Append an event after the currently selected event.",
        "icon": "mdi-shape-rectangle-plus",
        "name": "Append Event"
      },
      "prependEvent": {
        "group": "Editing",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "alt"
        ],
        "key": "-",
        "description": "Prepend an event before the currently selected event.",
        "icon": "mdi-shape-rectangle-plus",
        "iconClass": "mirror-horizontal",
        "name": "Prepend Event"
      },
      "deleteEvents": {
        "group": "Editing",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": true,
        "modifier": [],
        "key": "Backspace",
        "name": "Delete Events",
        "description": "Delete selected Events",
        "icon": "mdi-trash-can-outline"
      },
      "split": {
        "group": "Editing",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": true,
        "modifier": [],
        "key": "s",
        "name": "Split Event",
        "description": "Split an Event at the current play-head position.",
        "icon": "call_split"
      },
      "splitAtChar": {
        "group": "Editing",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "1",
        "name": "Split Event At Character",
        "description": "Split an Event at the Text Cursor position",
        "icon": "mdi-arrow-split-vertical"
      },
      "shiftCharsRight": {
        "group": "Editing",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd",
          "shift"
        ],
        "key": "r",
        "name": "Shift Characters Right",
        "description": "Shift characters to the next event",
        "icon": "mdi-format-letter-starts-with"
      },
      "shiftCharsLeft": {
        "group": "Editing",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd",
          "shift"
        ],
        "key": "l",
        "name": "Shift Characters Left",
        "description": "Shift characters to the previous event",
        "icon": "mdi-format-letter-ends-with"
      },
      "insertPause": {
        "group": "Editing",
        "greedy": true,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "p",
        "name": "Insert Pause",
        "description": "Insert a pause at the current cursor position",
        "icon": "pause_circle_outline"
      },
      "autoTranscribeEvent": {
        "group": "Editing",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd",
          "shift"
        ],
        "key": "k",
        "description": "Automatically Transcribe an Audio Segement",
        "icon": "mdi-text-to-speech",
        "name": "Auto-Transcribe Event"
      },
      "joinEvents": {
        "group": "Editing",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "j",
        "name": "Join Events",
        "icon": "merge_type",
        "description": "Join selected Events"
      },
      "moveEventStartLeft": {
        "group": "Editing",
        "greedy": true,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "alt"
        ],
        "key": "ArrowLeft",
        "name": "Move event start left",
        "description": "Move the beginning of an event to the left",
        "icon": "mdi-arrow-expand-left"
      },
      "moveEventStartRight": {
        "group": "Editing",
        "greedy": true,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "alt"
        ],
        "key": "ArrowRight",
        "name": "Move event start right",
        "description": "Move the beginning of an event to the right (use Shift to jump)",
        "icon": "mdi-arrow-collapse-right"
      },
      "moveEventEndRight": {
        "group": "Editing",
        "greedy": true,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "ArrowRight",
        "name": "Move event end right",
        "icon": "mdi-arrow-expand-right",
        "description": "Move the end of an event to the right (use Shift to jump)"
      },
      "moveEventEndLeft": {
        "group": "Editing",
        "greedy": true,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "ArrowLeft",
        "name": "Move event end left",
        "description": "Move the end of an event to the left (use Shift to jump)",
        "icon": "mdi-arrow-expand-left"
      },
      "showEditMenu": {
        "group": "Navigation",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "e",
        "name": "Show Edit Menu",
        "description": "Show the editing Options",
        "icon": "edit"
      },
      "showHistory": {
        "group": "Navigation",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd",
          "shift"
        ],
        "key": "h",
        "name": "Show History",
        "description": "Show the history",
        "icon": "history"
      },
      "showWarnings": {
        "group": "Navigation",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd",
          "shift"
        ],
        "key": "e",
        "name": "Show Warnings",
        "description": "Show Warnings in the Sidebar",
        "icon": "mdi-alert-outline"
      },
      "showTags": {
        "group": "Navigation",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd",
          "shift"
        ],
        "key": "b",
        "name": "Show Tags",
        "description": "Show Tags in the Sidebar",
        "icon": "bookmark_border"
      },
      "showSearch": {
        "group": "Navigation",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "f",
        "name": "Show Search",
        "description": "Focus the Search Field",
        "icon": "mdi-magnify"
      },
      "selectPreviousEvent": {
        "group": "Selection",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": true,
        "modifier": [],
        "key": "ArrowLeft",
        "name": "Select Previous Event",
        "description": "Select the Event before the currently selected Event",
        "icon": "mdi-arrow-left"
      },
      "selectNextEvent": {
        "group": "Selection",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": true,
        "modifier": [],
        "key": "ArrowRight",
        "name": "Select Next Event",
        "description": "Select the Event after the currently selected Event",
        "icon": "mdi-arrow-right"
      },
      "playPause": {
        "group": "Playback",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "Enter",
        "name": "Play/Pause",
        "description": "Play or Pause the currently selected Event",
        "icon": "mdi-play-pause"
      },
      "playFirstSecondOfEvent": {
        "group": "Playback",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd",
          "alt"
        ],
        "key": "Enter",
        "name": "Play start of Event",
        "description": "Play the first second of an Event",
        "icon": "mdi-contain-start"
      },
      "playLastSecondOfEvent": {
        "group": "Playback",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd",
          "shift"
        ],
        "key": "Enter",
        "name": "Play end of Event",
        "description": "Play the last second of an Event",
        "icon": "mdi-contain-end"
      },
      "scrollToEvent": {
        "group": "Navigation",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": true,
        "modifier": [],
        "key": "Enter",
        "name": "Scroll to Event",
        "description": "Scroll to the selected Event",
        "icon": "mdi-eye"
      },
      "inspectEvent": {
        "group": "Navigation",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "i",
        "name": "Inspect Event…",
        "description": "View audio analysis and event details",
        "icon": "mdi-sine-wave"
      },
      "selectAllEvents": {
        "group": "Selection",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": true,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "a",
        "name": "Select All",
        "description": "Selects all Events",
        "icon": "mdi-checkbox-marked-circle-outline"
      },
      "selectNone": {
        "group": "Selection",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "d",
        "name": "Select none",
        "description": "Selects no Events",
        "icon": "mdi-checkbox-blank-circle-outline"
      },
      "saveTranscript": {
        "group": "File",
        "greedy": false,
        "showInMenu": true,
        "ignoreInTextField": false,
        "modifier": [
          "ctrlOrCmd"
        ],
        "key": "s",
        "name": "Save Transcript",
        "description": "Save the Transcript to the Server",
        "icon": "save_alt"
      }
    },
    "lockPlayHead": false,
    "lockScroll": false,
    "minimumEventLength": 0.2,
    "maxEventGap": 1,
    "moveEventTimeByInterval": 0.2,
    "moveEventTimeByIntervalSmall": 0.01,
    "pixelsPerSecond": 100,
    "playbackSpeed": 0.26,
    "playbackVolume": 1,
    "showDrawer": false,
    "showSegmentBoxes": true,
    "showSpectrograms": false,
    "skipInterval": 1,
    "spectrogramColors": [
      {
        "at": 0,
        "c": [
          247,
          32,
          71,
          0
        ]
      },
      {
        "at": 128,
        "c": [
          100,
          149,
          237,
          1
        ]
      },
      {
        "at": 255,
        "c": [
          255,
          210,
          0,
          1
        ]
      }
    ],
    "spectrogramGradient": [
      [
        247,
        32,
        71,
        0
      ],
      [
        246,
        33,
        72,
        0.0078125
      ],
      [
        245,
        34,
        74,
        0.015625
      ],
      [
        244,
        35,
        75,
        0.0234375
      ],
      [
        242,
        36,
        76,
        0.03125
      ],
      [
        241,
        37,
        77,
        0.0390625
      ],
      [
        240,
        37,
        79,
        0.046875
      ],
      [
        239,
        38,
        80,
        0.0546875
      ],
      [
        238,
        39,
        81,
        0.0625
      ],
      [
        237,
        40,
        83,
        0.0703125
      ],
      [
        236,
        41,
        84,
        0.078125
      ],
      [
        234,
        42,
        85,
        0.0859375
      ],
      [
        233,
        43,
        87,
        0.09375
      ],
      [
        232,
        44,
        88,
        0.1015625
      ],
      [
        231,
        45,
        89,
        0.109375
      ],
      [
        230,
        46,
        90,
        0.1171875
      ],
      [
        229,
        47,
        92,
        0.125
      ],
      [
        227,
        48,
        93,
        0.1328125
      ],
      [
        226,
        48,
        94,
        0.140625
      ],
      [
        225,
        49,
        96,
        0.1484375
      ],
      [
        224,
        50,
        97,
        0.15625
      ],
      [
        223,
        51,
        98,
        0.1640625
      ],
      [
        222,
        52,
        100,
        0.171875
      ],
      [
        221,
        53,
        101,
        0.1796875
      ],
      [
        219,
        54,
        102,
        0.1875
      ],
      [
        218,
        55,
        103,
        0.1953125
      ],
      [
        217,
        56,
        105,
        0.203125
      ],
      [
        216,
        57,
        106,
        0.2109375
      ],
      [
        215,
        58,
        107,
        0.21875
      ],
      [
        214,
        59,
        109,
        0.2265625
      ],
      [
        213,
        59,
        110,
        0.234375
      ],
      [
        211,
        60,
        111,
        0.2421875
      ],
      [
        210,
        61,
        113,
        0.25
      ],
      [
        209,
        62,
        114,
        0.2578125
      ],
      [
        208,
        63,
        115,
        0.265625
      ],
      [
        207,
        64,
        116,
        0.2734375
      ],
      [
        206,
        65,
        118,
        0.28125
      ],
      [
        205,
        66,
        119,
        0.2890625
      ],
      [
        203,
        67,
        120,
        0.296875
      ],
      [
        202,
        68,
        122,
        0.3046875
      ],
      [
        201,
        69,
        123,
        0.3125
      ],
      [
        200,
        69,
        124,
        0.3203125
      ],
      [
        199,
        70,
        125,
        0.328125
      ],
      [
        198,
        71,
        127,
        0.3359375
      ],
      [
        196,
        72,
        128,
        0.34375
      ],
      [
        195,
        73,
        129,
        0.3515625
      ],
      [
        194,
        74,
        131,
        0.359375
      ],
      [
        193,
        75,
        132,
        0.3671875
      ],
      [
        192,
        76,
        133,
        0.375
      ],
      [
        191,
        77,
        135,
        0.3828125
      ],
      [
        190,
        78,
        136,
        0.390625
      ],
      [
        188,
        79,
        137,
        0.3984375
      ],
      [
        187,
        80,
        138,
        0.40625
      ],
      [
        186,
        80,
        140,
        0.4140625
      ],
      [
        185,
        81,
        141,
        0.421875
      ],
      [
        184,
        82,
        142,
        0.4296875
      ],
      [
        183,
        83,
        144,
        0.4375
      ],
      [
        182,
        84,
        145,
        0.4453125
      ],
      [
        180,
        85,
        146,
        0.453125
      ],
      [
        179,
        86,
        148,
        0.4609375
      ],
      [
        178,
        87,
        149,
        0.46875
      ],
      [
        177,
        88,
        150,
        0.4765625
      ],
      [
        176,
        89,
        151,
        0.484375
      ],
      [
        175,
        90,
        153,
        0.4921875
      ],
      [
        174,
        91,
        154,
        0.5
      ],
      [
        172,
        91,
        155,
        0.5078125
      ],
      [
        171,
        92,
        157,
        0.515625
      ],
      [
        170,
        93,
        158,
        0.5234375
      ],
      [
        169,
        94,
        159,
        0.53125
      ],
      [
        168,
        95,
        160,
        0.5390625
      ],
      [
        167,
        96,
        162,
        0.546875
      ],
      [
        165,
        97,
        163,
        0.5546875
      ],
      [
        164,
        98,
        164,
        0.5625
      ],
      [
        163,
        99,
        166,
        0.5703125
      ],
      [
        162,
        100,
        167,
        0.578125
      ],
      [
        161,
        101,
        168,
        0.5859375
      ],
      [
        160,
        101,
        170,
        0.59375
      ],
      [
        159,
        102,
        171,
        0.6015625
      ],
      [
        157,
        103,
        172,
        0.609375
      ],
      [
        156,
        104,
        173,
        0.6171875
      ],
      [
        155,
        105,
        175,
        0.625
      ],
      [
        154,
        106,
        176,
        0.6328125
      ],
      [
        153,
        107,
        177,
        0.640625
      ],
      [
        152,
        108,
        179,
        0.6484375
      ],
      [
        151,
        109,
        180,
        0.65625
      ],
      [
        149,
        110,
        181,
        0.6640625
      ],
      [
        148,
        111,
        183,
        0.671875
      ],
      [
        147,
        112,
        184,
        0.6796875
      ],
      [
        146,
        112,
        185,
        0.6875
      ],
      [
        145,
        113,
        186,
        0.6953125
      ],
      [
        144,
        114,
        188,
        0.703125
      ],
      [
        142,
        115,
        189,
        0.7109375
      ],
      [
        141,
        116,
        190,
        0.71875
      ],
      [
        140,
        117,
        192,
        0.7265625
      ],
      [
        139,
        118,
        193,
        0.734375
      ],
      [
        138,
        119,
        194,
        0.7421875
      ],
      [
        137,
        120,
        196,
        0.75
      ],
      [
        136,
        121,
        197,
        0.7578125
      ],
      [
        134,
        122,
        198,
        0.765625
      ],
      [
        133,
        122,
        199,
        0.7734375
      ],
      [
        132,
        123,
        201,
        0.78125
      ],
      [
        131,
        124,
        202,
        0.7890625
      ],
      [
        130,
        125,
        203,
        0.796875
      ],
      [
        129,
        126,
        205,
        0.8046875
      ],
      [
        128,
        127,
        206,
        0.8125
      ],
      [
        126,
        128,
        207,
        0.8203125
      ],
      [
        125,
        129,
        208,
        0.828125
      ],
      [
        124,
        130,
        210,
        0.8359375
      ],
      [
        123,
        131,
        211,
        0.84375
      ],
      [
        122,
        132,
        212,
        0.8515625
      ],
      [
        121,
        133,
        214,
        0.859375
      ],
      [
        120,
        133,
        215,
        0.8671875
      ],
      [
        118,
        134,
        216,
        0.875
      ],
      [
        117,
        135,
        218,
        0.8828125
      ],
      [
        116,
        136,
        219,
        0.890625
      ],
      [
        115,
        137,
        220,
        0.8984375
      ],
      [
        114,
        138,
        221,
        0.90625
      ],
      [
        113,
        139,
        223,
        0.9140625
      ],
      [
        111,
        140,
        224,
        0.921875
      ],
      [
        110,
        141,
        225,
        0.9296875
      ],
      [
        109,
        142,
        227,
        0.9375
      ],
      [
        108,
        143,
        228,
        0.9453125
      ],
      [
        107,
        144,
        229,
        0.953125
      ],
      [
        106,
        144,
        231,
        0.9609375
      ],
      [
        105,
        145,
        232,
        0.96875
      ],
      [
        103,
        146,
        233,
        0.9765625
      ],
      [
        102,
        147,
        234,
        0.984375
      ],
      [
        101,
        148,
        236,
        0.9921875
      ],
      [
        100,
        149,
        237,
        1
      ],
      [
        101,
        149,
        235,
        1
      ],
      [
        102,
        150,
        233,
        1
      ],
      [
        104,
        150,
        231,
        1
      ],
      [
        105,
        151,
        230,
        1
      ],
      [
        106,
        151,
        228,
        1
      ],
      [
        107,
        152,
        226,
        1
      ],
      [
        109,
        152,
        224,
        1
      ],
      [
        110,
        153,
        222,
        1
      ],
      [
        111,
        153,
        220,
        1
      ],
      [
        112,
        154,
        218,
        1
      ],
      [
        113,
        154,
        216,
        1
      ],
      [
        115,
        155,
        215,
        1
      ],
      [
        116,
        155,
        213,
        1
      ],
      [
        117,
        156,
        211,
        1
      ],
      [
        118,
        156,
        209,
        1
      ],
      [
        120,
        157,
        207,
        1
      ],
      [
        121,
        157,
        205,
        1
      ],
      [
        122,
        158,
        203,
        1
      ],
      [
        123,
        158,
        202,
        1
      ],
      [
        124,
        159,
        200,
        1
      ],
      [
        126,
        159,
        198,
        1
      ],
      [
        127,
        160,
        196,
        1
      ],
      [
        128,
        160,
        194,
        1
      ],
      [
        129,
        161,
        192,
        1
      ],
      [
        131,
        161,
        190,
        1
      ],
      [
        132,
        161,
        188,
        1
      ],
      [
        133,
        162,
        187,
        1
      ],
      [
        134,
        162,
        185,
        1
      ],
      [
        135,
        163,
        183,
        1
      ],
      [
        137,
        163,
        181,
        1
      ],
      [
        138,
        164,
        179,
        1
      ],
      [
        139,
        164,
        177,
        1
      ],
      [
        140,
        165,
        175,
        1
      ],
      [
        141,
        165,
        174,
        1
      ],
      [
        143,
        166,
        172,
        1
      ],
      [
        144,
        166,
        170,
        1
      ],
      [
        145,
        167,
        168,
        1
      ],
      [
        146,
        167,
        166,
        1
      ],
      [
        148,
        168,
        164,
        1
      ],
      [
        149,
        168,
        162,
        1
      ],
      [
        150,
        169,
        160,
        1
      ],
      [
        151,
        169,
        159,
        1
      ],
      [
        152,
        170,
        157,
        1
      ],
      [
        154,
        170,
        155,
        1
      ],
      [
        155,
        171,
        153,
        1
      ],
      [
        156,
        171,
        151,
        1
      ],
      [
        157,
        172,
        149,
        1
      ],
      [
        159,
        172,
        147,
        1
      ],
      [
        160,
        173,
        146,
        1
      ],
      [
        161,
        173,
        144,
        1
      ],
      [
        162,
        173,
        142,
        1
      ],
      [
        163,
        174,
        140,
        1
      ],
      [
        165,
        174,
        138,
        1
      ],
      [
        166,
        175,
        136,
        1
      ],
      [
        167,
        175,
        134,
        1
      ],
      [
        168,
        176,
        132,
        1
      ],
      [
        170,
        176,
        131,
        1
      ],
      [
        171,
        177,
        129,
        1
      ],
      [
        172,
        177,
        127,
        1
      ],
      [
        173,
        178,
        125,
        1
      ],
      [
        174,
        178,
        123,
        1
      ],
      [
        176,
        179,
        121,
        1
      ],
      [
        177,
        179,
        119,
        1
      ],
      [
        178,
        180,
        118,
        1
      ],
      [
        179,
        180,
        116,
        1
      ],
      [
        181,
        181,
        114,
        1
      ],
      [
        182,
        181,
        112,
        1
      ],
      [
        183,
        182,
        110,
        1
      ],
      [
        184,
        182,
        108,
        1
      ],
      [
        185,
        183,
        106,
        1
      ],
      [
        187,
        183,
        105,
        1
      ],
      [
        188,
        184,
        103,
        1
      ],
      [
        189,
        184,
        101,
        1
      ],
      [
        190,
        185,
        99,
        1
      ],
      [
        192,
        185,
        97,
        1
      ],
      [
        193,
        186,
        95,
        1
      ],
      [
        194,
        186,
        93,
        1
      ],
      [
        195,
        186,
        91,
        1
      ],
      [
        196,
        187,
        90,
        1
      ],
      [
        198,
        187,
        88,
        1
      ],
      [
        199,
        188,
        86,
        1
      ],
      [
        200,
        188,
        84,
        1
      ],
      [
        201,
        189,
        82,
        1
      ],
      [
        203,
        189,
        80,
        1
      ],
      [
        204,
        190,
        78,
        1
      ],
      [
        205,
        190,
        77,
        1
      ],
      [
        206,
        191,
        75,
        1
      ],
      [
        207,
        191,
        73,
        1
      ],
      [
        209,
        192,
        71,
        1
      ],
      [
        210,
        192,
        69,
        1
      ],
      [
        211,
        193,
        67,
        1
      ],
      [
        212,
        193,
        65,
        1
      ],
      [
        214,
        194,
        63,
        1
      ],
      [
        215,
        194,
        62,
        1
      ],
      [
        216,
        195,
        60,
        1
      ],
      [
        217,
        195,
        58,
        1
      ],
      [
        218,
        196,
        56,
        1
      ],
      [
        220,
        196,
        54,
        1
      ],
      [
        221,
        197,
        52,
        1
      ],
      [
        222,
        197,
        50,
        1
      ],
      [
        223,
        198,
        49,
        1
      ],
      [
        224,
        198,
        47,
        1
      ],
      [
        226,
        198,
        45,
        1
      ],
      [
        227,
        199,
        43,
        1
      ],
      [
        228,
        199,
        41,
        1
      ],
      [
        229,
        200,
        39,
        1
      ],
      [
        231,
        200,
        37,
        1
      ],
      [
        232,
        201,
        35,
        1
      ],
      [
        233,
        201,
        34,
        1
      ],
      [
        234,
        202,
        32,
        1
      ],
      [
        235,
        202,
        30,
        1
      ],
      [
        237,
        203,
        28,
        1
      ],
      [
        238,
        203,
        26,
        1
      ],
      [
        239,
        204,
        24,
        1
      ],
      [
        240,
        204,
        22,
        1
      ],
      [
        242,
        205,
        21,
        1
      ],
      [
        243,
        205,
        19,
        1
      ],
      [
        244,
        206,
        17,
        1
      ],
      [
        245,
        206,
        15,
        1
      ],
      [
        246,
        207,
        13,
        1
      ],
      [
        248,
        207,
        11,
        1
      ],
      [
        249,
        208,
        9,
        1
      ],
      [
        250,
        208,
        7,
        1
      ],
      [
        251,
        209,
        6,
        1
      ],
      [
        253,
        209,
        4,
        1
      ],
      [
        254,
        210,
        2,
        1
      ],
      [
        255,
        210,
        0,
        1
      ]
    ],
    "projectPreset": "PP04",
    "useMonoWaveForm": false,
    "waveFormColors": [
      "#fb7676",
      "#187CE0"
    ],
    "placeholderToken": "⦿",
    "playEventOnAppend": true,
    "scrollSpeed": 1,
    "showWarnings": {
      "eventGaps": true,
      "unknownTokenTypes": true,
      "eventOverlaps": true
    }
  },
  "audio": {
    "currentTime": 0,
    "duration": 0,
    "fileSize": 0,
    "isPaused": true,
    "playAllFromTime": null,
    "url": "https://dioedb.demo.dioe.at/private-media/ai04/4042_WIEW_alt_w_AI.ogg"
  }
}
[transcribe-dev.dioe.at-1653307146209.log](https://github.com/german-in-austria/transcribe/files/8754306/transcribe-dev.dioe.at-1653307146209.log)
`
