### ISSUE TITLE
Neue Events werden bei Speichern erzeugt

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/transcribe#42]
Den Grazer:innen ist aufgefallen, dass anscheinend teilweise beim Speichern eines Transkripts neue Events (?) erzeugt werden (konkret bei den Transkripten 4088_GRAG_jung_m_AI und 4093_GRAW_alt_m_AI). Systematik dahinter konnten sie keine finden, für das 4093_GRAW_alt_m_AI - Transkript hat mir die Ann den Log geschickt. So hat das nach dem Speichern ausgesehen:

![image](https://user-images.githubusercontent.com/60658004/176168952-656b338e-8223-47d5-aa8f-966ad0949e92.png)

Ann meinte, dass die Events nicht so kleinteilig waren, der Log is anbei!

[transcribe.dioe.at-1656414970925.log](https://github.com/german-in-austria/transcribe/files/9000599/transcribe.dioe.at-1656414970925.log)

**Comment by hcb79** [comment]
Die müssten eigentlich eine Meldung bekommen haben das das abspeichern nicht funktioniert hat.
So wie ich das sehe kommt es beim Abspeichern zu einem Timeout, ein Teil ist abgespeichert und das Transcibe Tool weis es nicht ... wenn man dann erneut auf speichern klickt wird dieser Teil doppelt abgespeichert ...
Das wird komplizierter ... bin dran.

**Comment by MarkusPluschkovits** [comment]
fixed, danke! :)
